### PR TITLE
Add Dockerfile

### LINKED ISSUE #162: Dockerfile
Hello

I wanted to create a Dockerfile to run explainshell locally. I am not very good with docker so maybe you would help me out a little?

Dockerfile
```Dockerfile
FROM python:3.4

MAINTAINER Simon Toivo Telhaug  <simon.toivo@example.com>

ADD ./requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip
RUN python --version
RUN pip install -r /tmp/requirements.txt

ADD ./ /opt/webapp/
WORKDIR /opt/webapp
EXPOSE 5000

CMD ["make", "serve"]
# CMD ["python", "app.py"]
```
and I get det following when trying to build
```bash
$ docker build -t explainshell .
Sending build context to Docker daemon 3.571 MB
Step 1 : FROM python:3.4
3.4: Pulling from library/python
...
Removing intermediate container 68d0852b8462
Step 5 : RUN python --version
 ---> Running in 9107aa29433a
Python 3.4.5
 ---> 164548d34350
Removing intermediate container 9107aa29433a
Step 6 : RUN pip install -r /tmp/requirements.txt
 ---> Running in f086bd311b0a
Collecting MarkupSafe==0.23 (from -r /tmp/requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Flask==0.10.1 (from -r /tmp/requirements.txt (line 2))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting nltk==2.0.5 (from -r /tmp/requirements.txt (line 3))
  Downloading nltk-2.0.5.tar.gz (954kB)
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpq38kqtie
    Now working in /tmp/tmpq38kqtie/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-6v_7dv9o/nltk
    creating build
    creating build/src
    creating build/src/docs
    creating build/src/docs/_templates
    creating build/src/docs/_theme
    creating build/src/docs/_theme/nature
    creating build/src/docs/_theme/nature/static
    creating build/src/docs/build
    creating build/src/docs/build/html
    creating build/src/docs/build/html/_sources
    creating build/src/docs/build/html/_static
    creating build/src/setuptools
    creating build/src/setuptools/command
    creating build/src/setuptools/tests
    creating build/src/setuptools/tests/indexes
    creating build/src/setuptools/tests/indexes/test_links_priority
    creating build/src/setuptools/tests/indexes/test_links_priority/simple
    creating build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
    creating build/src/tests
    creating build/src/tests/shlib_test
    copying setuptools/package_index.py -> build/src/setuptools
    copying setuptools/extension.py -> build/src/setuptools
    copying setuptools/depends.py -> build/src/setuptools
    copying setuptools/archive_util.py -> build/src/setuptools
    copying setuptools/__init__.py -> build/src/setuptools
    copying setuptools/sandbox.py -> build/src/setuptools
    copying setuptools/dist.py -> build/src/setuptools
    copying setuptools/tests/test_packageindex.py -> build/src/setuptools/tests
    copying setuptools/tests/test_develop.py -> build/src/setuptools/tests
    copying setuptools/tests/test_easy_install.py -> build/src/setuptools/tests
    copying setuptools/tests/test_upload_docs.py -> build/src/setuptools/tests
    copying setuptools/tests/test_sandbox.py -> build/src/setuptools/tests
    copying setuptools/tests/test_resources.py -> build/src/setuptools/tests
    copying setuptools/tests/server.py -> build/src/setuptools/tests
    copying setuptools/tests/__init__.py -> build/src/setuptools/tests
    copying setuptools/tests/test_build_ext.py -> build/src/setuptools/tests
    copying setuptools/tests/doctest.py -> build/src/setuptools/tests
    copying setuptools/command/install.py -> build/src/setuptools/command
    copying setuptools/command/register.py -> build/src/setuptools/command
    copying setuptools/command/upload.py -> build/src/setuptools/command
    copying setuptools/command/egg_info.py -> build/src/setuptools/command
    copying setuptools/command/install_lib.py -> build/src/setuptools/command
    copying setuptools/command/setopt.py -> build/src/setuptools/command
    copying setuptools/command/upload_docs.py -> build/src/setuptools/command
    copying setuptools/command/rotate.py -> build/src/setuptools/command
    copying setuptools/command/test.py -> build/src/setuptools/command
    copying setuptools/command/build_py.py -> build/src/setuptools/command
    copying setuptools/command/bdist_egg.py -> build/src/setuptools/command
    copying setuptools/command/saveopts.py -> build/src/setuptools/command
    copying setuptools/command/bdist_rpm.py -> build/src/setuptools/command
    copying setuptools/command/easy_install.py -> build/src/setuptools/command
    copying setuptools/command/install_egg_info.py -> build/src/setuptools/command
    copying setuptools/command/__init__.py -> build/src/setuptools/command
    copying setuptools/command/bdist_wininst.py -> build/src/setuptools/command
    copying setuptools/command/alias.py -> build/src/setuptools/command
    copying setuptools/command/build_ext.py -> build/src/setuptools/command
    copying setuptools/command/develop.py -> build/src/setuptools/command
    copying setuptools/command/install_scripts.py -> build/src/setuptools/command
    copying setuptools/command/sdist.py -> build/src/setuptools/command
    copying setuptools/tests/win_script_wrapper.txt -> build/src/setuptools/tests
    copying setuptools/cli.exe -> build/src/setuptools
    copying setuptools/gui.exe -> build/src/setuptools
    copying tests/test_distribute_setup.py -> build/src/tests
    copying tests/install_test.py -> build/src/tests
    copying tests/manual_test.py -> build/src/tests
    copying tests/shlib_test/setup.py -> build/src/tests/shlib_test
    copying tests/shlib_test/test_hello.py -> build/src/tests/shlib_test
    copying tests/shlib_test/hellolib.c -> build/src/tests/shlib_test
    copying tests/shlib_test/hello.c -> build/src/tests/shlib_test
    copying tests/shlib_test/hello.pyx -> build/src/tests/shlib_test
    copying tests/api_tests.txt -> build/src/tests
    RefactoringTool: Skipping optional fixer: buffer
    RefactoringTool: Skipping optional fixer: idioms
    RefactoringTool: Skipping optional fixer: set_literal
    RefactoringTool: Skipping optional fixer: ws_comma
    RefactoringTool: Refactored build/src/tests/api_tests.txt
    RefactoringTool: Files that were modified:
    RefactoringTool: build/src/tests/api_tests.txt
    --- build/src/tests/api_tests.txt (original)
    +++ build/src/tests/api_tests.txt (refactored)
    @@ -39,7 +39,7 @@
         >>> dist.py_version == sys.version[:3]
         True

    -    >>> print dist.platform
    +    >>> print(dist.platform)
         None

     Including various computed attributes::
    @@ -199,7 +199,7 @@
     You can ask a WorkingSet to ``find()`` a distribution matching a requirement::

         >>> from pkg_resources import Requirement
    -    >>> print ws.find(Requirement.parse("Foo==1.0"))    # no match, return None
    +    >>> print(ws.find(Requirement.parse("Foo==1.0")))    # no match, return None
         None

         >>> ws.find(Requirement.parse("Bar==0.9"))  # match, return distribution
    @@ -211,7 +211,7 @@
         >>> try:
         ...     ws.find(Requirement.parse("Bar==1.0"))
         ... except VersionConflict:
    -    ...     print 'ok'
    +    ...     print('ok')
         ok

     You can subscribe a callback function to receive notifications whenever a new
    @@ -219,7 +219,7 @@
     once for each existing distribution in the working set, and then is called
     again for new distributions added thereafter::

    -    >>> def added(dist): print "Added", dist
    +    >>> def added(dist): print("Added", dist)
         >>> ws.subscribe(added)
         Added Bar 0.9
         >>> foo12 = Distribution(project_name="Foo", version="1.2", location="f12")
    copying setuptools/tests/indexes/test_links_priority/external.html -> build/src/setuptools/tests/indexes/test_links_priority
    copying setuptools/tests/indexes/test_links_priority/simple/foobar/index.html -> build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
    copying docs/conf.py -> build/src/docs
    copying docs/python3.txt -> build/src/docs
    copying docs/easy_install.txt -> build/src/docs
    copying docs/setuptools.txt -> build/src/docs
    copying docs/roadmap.txt -> build/src/docs
    copying docs/using.txt -> build/src/docs
    copying docs/index.txt -> build/src/docs
    copying docs/pkg_resources.txt -> build/src/docs
    copying docs/build/html/_sources/python3.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/easy_install.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/setuptools.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/roadmap.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/using.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/index.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/pkg_resources.txt -> build/src/docs/build/html/_sources
    copying docs/_theme/nature/theme.conf -> build/src/docs/_theme/nature
    copying docs/_theme/nature/static/pygments.css -> build/src/docs/_theme/nature/static
    copying docs/build/html/_static/pygments.css -> build/src/docs/build/html/_static
    copying docs/build/html/_static/nature.css -> build/src/docs/build/html/_static
    copying docs/build/html/_static/basic.css -> build/src/docs/build/html/_static
    copying docs/_theme/nature/static/nature.css_t -> build/src/docs/_theme/nature/static
    copying docs/Makefile -> build/src/docs
    copying docs/_templates/indexsidebar.html -> build/src/docs/_templates
    copying site.py -> build/src
    copying pkg_resources.py -> build/src
    copying setup.py -> build/src
    copying easy_install.py -> build/src
    copying distribute_setup.py -> build/src
    copying DEVGUIDE.txt -> build/src
    copying CHANGES.txt -> build/src
    copying README.txt -> build/src
    copying CONTRIBUTORS.txt -> build/src
    copying MANIFEST.in -> build/src
    copying launcher.c -> build/src
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_suite'
      warnings.warn(msg)
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: invalid command 'bdist_egg'
    /tmp/pip-build-6v_7dv9o/nltk/distribute-0.6.21-py3.4.egg
    Traceback (most recent call last):
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6v_7dv9o/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6v_7dv9o/nltk/
The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by stoivo**
closes #162

### CODE REVIEW

File: docker-compose.yml [hunk 1]
```diff
@@ -0,0 +1,13 @@
+version: '2'
+services:
+  db:
+    image: mongo
+  web:
```
Comment (arahayrabedian) [inline docker-compose.yml]: you can (should) define an `environment` section under web, something like:
```
environment:
 - MONGO_URI=mongodb://db
```
so that anybody running the docker-compose version will automatically talk to the mongo instance that is brought up by docker-compose.

File: docker-compose.yml [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+    build: .
+    command: CMD make serve
```
Comment (stoivo) [inline docker-compose.yml]: I think this should be without CMD?

File: docker-compose.yml (hunk 1 above)
Comment (stoivo) [inline docker-compose.yml]: Done

**Comment by stoivo** [comment]
Where should I put `mongorestore dump/explainshell`?

Who do I run tests ?
`mongorestore -d explainshell_tests dump/explainshell`

**Comment by arahayrabedian** [comment]
that looks like it gets a little complicated...

two ways to look at it:
1) it's not the responsibility of the application since it's a mongorestore
2) it's the responsibility of the application and you now have two choices
 - i) install a mongo client in the explainshell container
 - ii) do this from the host instructing the mongo container, like:

```
➜  explainshell git:(master) ✗ docker cp dump/ explainshell_db_1:/tmp/dump
➜  explainshell git:(master) ✗ docker exec explainshell_db_1 mongorestore /tmp/dump                          
2016-11-14T12:27:01.395+0000	building a list of dbs and collections to restore from /tmp/dump dir
2016-11-14T12:27:01.400+0000	no metadata; falling back to system.indexes
2016-11-14T12:27:01.409+0000	restoring explainshell.classifier from /tmp/dump/explainshell/classifier.bson
2016-11-14T12:27:01.431+0000	restoring indexes for collection explainshell.classifier from metadata
2016-11-14T12:27:01.440+0000	finished restoring explainshell.classifier (517 documents)
2016-11-14T12:27:01.440+0000	done
```


not sure what the second command is supposed to do but i tried these two:

```
➜  explainshell git:(master) ✗ docker exec explainshell_db_1 mongorestore -d explainshell_tests /tmp/dump
2016-11-14T12:35:00.037+0000	building a list of collections to restore from /tmp/dump dir
2016-11-14T12:35:00.037+0000	don't know what to do with subdirectory "dump/explainshell", skipping...
2016-11-14T12:35:00.037+0000	done
➜  explainshell git:(master) ✗ docker exec explainshell_db_1 mongorestore -d explainshell_tests /tmp/dump/explainshell
2016-11-14T12:35:11.161+0000	building a list of collections to restore from /tmp/dump/explainshell dir
2016-11-14T12:35:11.163+0000	no metadata; falling back to system.indexes
2016-11-14T12:35:11.175+0000	restoring explainshell_tests.classifier from /tmp/dump/explainshell/classifier.bson
2016-11-14T12:35:11.195+0000	restoring indexes for collection explainshell_tests.classifier from metadata
2016-11-14T12:35:11.203+0000	finished restoring explainshell_tests.classifier (517 documents)
2016-11-14T12:35:11.203+0000	done
```

**Comment by stoivo** [comment]
I am fine with importing database with a script manual if that is the docker way.

Currently I would like to make the test pass. I do the following steps:
docker-compose up --build
docker cp dump/ explainshell_db_1:/tmp/dump
docker exec explainshell_db_1 mongorestore -d explainshell_tests /tmp/dump/explainshell

docker exec explainshell_web_1 make tests

```python
nosetests --with-doctest tests/ explainshell/
..EEEEEEEEE....................................................................
======================================================================
ERROR: test (tests.test-integration.test_integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/webapp/tests/test-integration.py", line 8, in test
    mngr.run()
  File "/opt/webapp/explainshell/manager.py", line 113, in run
    m = self.process(ctx)
  File "/opt/webapp/explainshell/manager.py", line 71, in process
    self._read(ctx, frunner)
  File "/opt/webapp/explainshell/manager.py", line 40, in _read
    ctx.manpage.read()
  File "/opt/webapp/explainshell/manpage.py", line 187, in read
    self.synopsis = subprocess.check_output(['lexgrog', self.path], stderr=devnull).rstrip()
  File "/usr/local/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------- >> begin captured logging << --------------------
explainshell.store: INFO: creating store, db = 'explainshell_tests', host = 'mongodb://db'
explainshell.algo.classifier: INFO: train on 994 instances
explainshell.store: INFO: dropping mapping, manpage, collections
explainshell.manager: INFO: handling manpage echo (from /opt/webapp/tests/echo.1.gz)
explainshell.store: INFO: looking up manpage in mapping with src 'echo'
explainshell.manpage: INFO: executing '/opt/webapp/tools/w3mman2html.cgi local=%2Fopt%2Fwebapp%2Ftests%2Fecho.1.gz'
explainshell.manager: CRITICAL: uncaught exception when handling manpage /opt/webapp/tests/echo.1.gz
--------------------- >> end captured logging << ---------------------
...
FAILED (errors=9)
Makefile:2: recipe for target 'tests' failed
make: *** [tests] Error 1
```

I dont know why the spec is failing. I look like it is because /opt/webapp/tests/echo.1.gz doesn't exist but it does.

**Comment by stoivo** [comment]
Is the an easy way to delete all contained? or reset them to build status?

**Comment by arahayrabedian** [comment]
not sure what you mean exactly @stoivo 

they never really had a clean way on docker for the most part, not sure if that's improved. But I definitely know you can put together something with a combination of `docker ps -a`, `docker ps -aq`, `docker rm`, `docker rmi` and a bunch of shell kung-fu

**Comment by idank** [comment]
It appears to be failing because `lexgrog` isn't installed:

    self.synopsis = subprocess.check_output(['lexgrog', self.path], stderr=devnull).rstrip()

**Comment by stoivo** [comment]
@arahayrabedian, sorry for my typos. What I tried to ask for was a way to remove all docker containers and all docker images. As I understand from the is no official way to move those but is it quite easy to create with the -q options to docker. 

Do you want to share some of you kung-fu skills?

@idank I installed man-db, it that correct?
Now it looks like test are passing.

**Comment by arahayrabedian** [comment]
https://gist.github.com/arahayrabedian/e487a8d9325a7f9320cc#file-useful_aliases-L5
should get you started for cleaning up images without a tag.

and `docker rm $(docker ps -aq)` should remove any containers that have terminated but are still around, i'd be careful with this one as there's a possibility to delete containers that may have important state in them (especially data-only container pattern)

for that i use something more like:

`alias dockerclean='docker rm $(docker ps -a | grep -v sql | grep -v postgres | grep -v elasticsearch | grep -v redis | cut -d" " -f1)'`

where you have to take care to pay attention to what's important to you, i've personally retired this alias (i.e: i've not run it in a while) as i don't use docker day-to-day anymore (left the industry, doing my masters)

there will be hiccups solved by `-f`'ing here and there

**Comment by arahayrabedian** [comment]
side note, i don't know if you'll continue using docker in the future, but you'll save yourself thousands of keystrokes with [this alias](https://gist.github.com/arahayrabedian/e487a8d9325a7f9320cc#file-useful_aliases-L12-L15)

File: README.md [hunk 3]
```diff
@@ -74,3 +74,26 @@ Use the manager to parse and save a gzipped man page in raw format:
...
+    $ docker-compose up
+
+    Copy dump over to container for than to import it.
+    $ docker cp dump/ explainshell_db_1:/tmp/dump
+
+    Import classifiers
+    $ docker exec explainshell_db_1 mongorestore /tmp/dump
+
+    Open browser at port 5000
+    $ open http://localhost:5000
```
Comment (arahayrabedian) [inline README.md]: i think this assumes OSX?

**Comment by arahayrabedian** [comment]
either way, awesome stuff, i hope it wasn't too hard picking up docker @stoivo ?

**Comment by stoivo** [comment]
@arahayrabedian, nice. Nice tools for further use of docker. 
I have been using virtualBox to make multiple machines before. I think I will try to convert some those that are active.

@idank, how do I import a new man page?
I did these steps:
```bash
apt-get install rsync
man rsync > manpages/1/rsync.1
cd manpages/1/
gzip rsync.1
cd ../..
PYTHONPATH=. python explainshell/manager.py --log info manpages/1/rsync.1.gz
```
After doing these steps it did not import any arguments.

I gunzip tar.1.gz and that one look allot differently that the `man rsync`?
I guess I should do something with the man page before gziping it.

**Comment by idank** [comment]
You can also get them online from Ubuntu's archive. Search for gz on this page: http://manpages.ubuntu.com/manpages/xenial/en/man1/echo.1.html

**Comment by stoivo** [comment]
@arahayrabedian it have been interesting to check how I can use docker in develment. 

@idank I will try that this weekend

File: README.md (hunk 3 above)
Comment (stoivo) [inline README.md]: Yes, I think so. I think it can be configured other platforms.

Maybe remove it?

**Comment by stoivo** [comment]
@idank it works awesome.

**Comment by stoivo** [comment]
I think I should write something more more how to set up a dev environment.

**Comment by stoivo** [comment]
Hello

@idank, I wonder if it something more I should do before we can merge this?
Maybe we should right something about importing all man pages that is in use in production?
and link to https://github.com/idank/explainshell-manpages if you uses this? I guess you have a different structure since this is not updated in 3 years

**Comment by stoivo** [comment]
@arahayrabedian is there a way I can reach you when I have some question about Docker that I can't figure out?

**Comment by arahayrabedian** [comment]
@stoivo certainly; you're welcome to email me: ara.hayrabedian at the gmails, or AHayrabedian on twitter, am less likely to see that one though.

File: requirements.txt [hunk 4]
```diff
@@ -1,6 +1,6 @@
 Flask==0.10.1
 MarkupSafe==0.23
-nltk==2.0.4
+nltk==2.0.5
```
Comment (idank) [inline requirements.txt]: why is this needed?

File: runserver.py [hunk 5]
```diff
@@ -5,4 +5,4 @@
 logging.config.dictConfig(config.LOGGING_DICT)
 
 if __name__ == '__main__':
-    app.run(debug=config.DEBUG)
+    app.run(debug=config.DEBUG, host='0.0.0.0')
```
Comment (idank) [inline runserver.py]: can you find a way to do this only for the docker setup? I don't like it if I'm running on a host with a public ip

File: explainshell/config.py [hunk 6]
```diff
@@ -8,7 +8,7 @@
 
 MAN2HTML = os.path.join(TOOLSDIR, 'w3mman2html.cgi')
 
-MONGO_URI = 'mongodb://localhost'
+MONGO_URI = os.getenv('MONGO_URI', 'mongodb://localhost')
```
Comment (idank) [inline explainshell/config.py]: can't docker setup its own config.py with the right address?

File: requirements.txt (hunk 4 above)
Comment (stoivo) [inline requirements.txt]: Otherwise I get this error message
```
Collecting nltk==2.0.4 (from -r /tmp/requirements.txt (line 3))
  Downloading nltk-2.0.4.zip (1.1MB)
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpdkKrvN
    Now working in /tmp/tmpdkKrvN/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-sqfCM2/nltk
    /tmp/pip-build-sqfCM2/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sqfCM2/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sqfCM2/nltk/
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

Comment (idank) [inline requirements.txt]: Ok, found https://github.com/nltk/nltk/issues/824 which explains the issue. Hopefully no other changes creeped into 2.0.5.

File: runserver.py (hunk 5 above)
Comment (stoivo) [inline runserver.py]: Is this better?
```python
if __name__ == '__main__':
    host = os.getenv('HOST_IP', False)
    if host:
        app.run(debug=config.DEBUG, host=host)
    else:
        app.run(debug=config.DEBUG)
```

File: explainshell/config.py (hunk 6 above)
Comment (stoivo) [inline explainshell/config.py]: Would you like to have one file called config.py and config_docker.py?

Maybe I missunderstood something.

Comment (idank) [inline explainshell/config.py]: Instead of adding all these environment variables, I'm suggesting that a setup phase in docker (not sure what it's called) will write a new config.py that replaces the existing one, with the new values for the things it cares about, like MONGO_URI (and HOST it seems).

As a middle ground, I guess we could add something like this at the end of config.py:

```
# load additional config from an out-of-tree file
if os.getenv('ADDITIONAL_CONFIG'):
  execfile(os.getenv('ADDITIONAL_CONFIG'))
``` 

Then you can override the values you want in another config file and set the environment variable once.

File: requirements.txt (hunk 4 above)
Comment (stoivo) [inline requirements.txt]: Cool, thanks for investigating. I would never find that.

File: explainshell/config.py (hunk 6 above)
Comment (stoivo) [inline explainshell/config.py]: Check it now.

File: runserver.py (hunk 5 above)
Comment (stoivo) [inline runserver.py]: Now I use config.HOST_IP

**Comment by stoivo** [comment]
I make 3 commit. This is better

**Comment by idank** [comment]
I merged your changes with small modifications. Can you test it please? Thanks!

**Comment by idank** [comment]
It doesn't seem to work for me. The command `sudo docker exec explainshell_web_1 PYTHONPATH=. python explainshell/manager.py --log info /usr/share/man/man1/rsync.1.gz` is failing because it's taking the first argument as the program name. I guess we need to run it with bash -c.

Are you sure the instructions in the readme work?

**Comment by idank** [comment]
Also it seems like the container I got doesn't have rsync.1.gz.

**Comment by stoivo** [comment]
it did not work either. After your update it works good.
